"PORT" = 3001
"JWT_EXPIRES_IN"="1d"
"JWT_SECRET"="secret"
"MAIL_HOST"="smtp.gmail.com"
"GOOGLE_SECRET"=""
"MAILING_SERVICE_CLIENT_ID"="869158533196-tsuh873ruj92emjub2uqi8iu0rqnvq27.apps.googleusercontent.com"
"MAIL_PASSWORD"=""
"MAIL_PORT"=465
"MAIL_USERNAME"="example@gmail.com"
"STRIPE_KEY"=""
"FRONT_URL"=""
